# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.9]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: sh tools/setup.sh
      - name: Lint Codebase
        run: sh tools/lint.sh
      - name: Build Wheel
        run: sh tools/build.sh
      - name: Test Wheel
        env:
          GCS_CREDENTIALS: ${{ secrets.GCS_CREDENTIALS }}
        run: rm -rf ./pathy/ && sh tools/test_package.sh
      - name: Report Code Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: sh tools/codecov.sh

  deploy:
    runs-on: ubuntu-latest
    needs: "build"
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Deploy
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sh tools/deploy.sh
